<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="Microsoft.Data.Sqlite" />
    <PackageReference Include="SQLitePCLRaw.bundle_e_sqlite3" />
    <PackageReference Include="Newtonsoft.Json" />
    <PackageReference Include="SpotifyAPI.Web" />
    <PackageReference Include="SpotifyAPI.Web.Auth" />
  </ItemGroup>

</Project>
